# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-aws-credentials
      - id: check-added-large-files
        exclude: "(reference/docker-getting-started)/.*"
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
        exclude: "(.github)/.*"
      - id: end-of-file-fixer
        exclude: ".*.svg"
      - id: trailing-whitespace
        exclude: "(\\.terraform(/.*)?$|tests/.*)"
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        exclude: "(reference)/.*"
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py3-plus
          - --keep-runtime-typing
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.260
    hooks:
      - id: ruff
        files: \.py$
        exclude: "(reference)/.*"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        additional_dependencies: [toml]
        files: \.py$
        exclude: ^.*/?setup\.py$
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: \.py$
        exclude: "(reference|tests)/.*"
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.41.0
    hooks:
      - id: eslint
        files: "(.*/review-app/frontend/)"
        types: [file, javascript, jsx, ts, tsx]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: "(.*/review-app/frontend/)"
        types: [css, json, javascript, ts, jsx, tsx]

ci:
  autofix_commit_msg: 🎨 [pre-commit.ci] Auto format from pre-commit.com hooks
  autoupdate_commit_msg: ⬆ [pre-commit.ci] pre-commit autoupdate
