FROM ubuntu:20.04

RUN set -x \
&& apt-get update \
&& apt-get install -y python3 python3-pip \
&& apt-get install -y python3.7 \
&& apt-get install -y python3.8 \
&& apt-get install -y python3.9 \
&& apt-get install -y python3.10 \
&& apt-get install -y python3.11
