default_context:
  project_name: 'fullstackfastapi'
  project_slug: 'fullstackfastapi'
  domain_main: 'fullstackfastapi.eomiso.me'
  domain_staging: 'stag.fullstackfastapi.eomiso.me'
  docker_swarm_stack_name_main: 'fullstackfastapi-eomiso-me'
  docker_swarm_stack_name_staging: 'stag-fullstackfastapi-eomiso-me'
  secret_key: '6b39548239d92df4447c65ca82baefa7b2b2f977ff0f3dabe7302b0a6629ada1'
  first_superuser: 'ytrtef@gmail.com'
  first_superuser_password: '52regt!@#'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fullstackfastapi.eomiso.me", "https://stag.fullstackfastapi.eomiso.me", "https://fullstackfastapi.eomiso.me", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp.sparkpostmail.com'
  smtp_user: 'SMTP_Injection'
  smtp_password: '4168e25e8cc64e3002f1bf3ff9d33a96d42fea4f'
  smtp_emails_from_email: 'info@fullstackfastapi.eomiso.me'
  postgres_password: '1111'
  pgadmin_default_user: 'ytrtef@gmail.com'
  pgadmin_default_user_password: '52regt!@#'
  traefik_constraint_tag: 'fullstackfastapi.eomiso.me'
  traefik_constraint_tag_staging: 'stag.fullstackfastapi.eomiso.me'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:52regt!@#'
  sentry_dsn: 'https://5f807c01ddbb45bb9c408589203c2420@o1124236.ingest.sentry.io/6162525'
  docker_image_prefix: 'fullstackfastapi'
  docker_image_backend: 'fullstackfastapibackend'
  docker_image_celeryworker: 'fullstackfastapiceleryworker'
  docker_image_frontend: 'fullstackfastapifrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
