name: cronjob-for-auto-merging-dev-to-main
on:
  schedule:
    - cron: "1 15 * * 0"
  workflow_dispatch:
    inputs:
      LogLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  merge-dev-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        run: |
          git branch
          git checkout dev
      # https://github.com/marketplace/actions/github-pull-request-action
      - name: create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
          pr_reviewer: "eomiso"
          pr_assignee: "eomiso"

      - name: Auto merge PR to main
        if: steps.open-pr.outputs.pr_number != ''
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
          merge-method: merge
