name: Docker Hub Push

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    paths:
      - "incubator/node-frontend/**"
      - ".github/workflows/node-frontend.yml"
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    defaults:
      run:
        working-directory: ./incubator/node-frontend
    runs-on: ubuntu-latest
    steps:
      - run: |
          sh scripts/build_push.sh
