name: Docker Hub Push

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    paths:
      - "incubator/node-frontend/**"
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    env:
      working-directory: ./incubator/node-frontend
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          sh scripts/build-push.sh
