name: Docker Hub Push

run-name: ${{ github.actor }} is Pushing Node Frontend Docker Image 🚀

on:
  push:
    paths:
      - "incubator/node-frontend/**"
      - ".github/workflows/node-frontend.yml"
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    env:
      working-directory: incubator/node-frontend
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
          sh scripts/build-push.sh
